// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycjvzprutoquitlldytq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljanZ6cHJ1dG9xdWl0bGxkeXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzI1NDMsImV4cCI6MjA3NDkwODU0M30.B5iy7_myAwP1aIqIGHOmO_HoD2blw-wCA0ZwIQNWd1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});